[default.extend-words]
nin = "nin"
nd = "nd"
Strat = "Strat"
eles = "eles"
ser = "ser"
isconnection = "isconnection"
Ue = "Ue"
Derivate = "Derivate"
Nd = "Nd"
coul = "coul"
setp = "setp"
getp = "getp"
indexin = "indexin"
ists = "ists"
ispcs = "ispcs"
eqs = "eqs"
rhs = "rhs"
MTK = "MTK"
