[default.extend-words]
nin = "nin"
nd = "nd"
Strat = "Strat"
eles = "eles"
ser = "ser"
isconnection = "isconnection"
Ue = "Ue"
Derivate = "Derivate"
missings = "missings"
alph = "alph"
fo = "fo"
shs = "shs"
setp = "setp"
CMO = "CMO"
Lamba = "Lamba"
gam = "gam"
