pages = [
    "Home" => "index.md",
    "Symbolic Modeling Tutorials" => Any["tutorials/ode_modeling.md",
                                         "tutorials/spring_mass.md",
                                         "tutorials/acausal_components.md",
                                         "tutorials/higher_order.md",
                                         "tutorials/tearing_parallelism.md",
                                         "tutorials/nonlinear.md",
                                         "tutorials/optimization.md",
                                         "tutorials/stochastic_diffeq.md",
                                         "tutorials/parameter_identifiability.md"],
    "ModelingToolkitize Tutorials" => Any["mtkitize_tutorials/modelingtoolkitize.md",
                                          "mtkitize_tutorials/modelingtoolkitize_index_reduction.md",
                                          "mtkitize_tutorials/sparse_jacobians.md"],
    "Basics" => Any["basics/AbstractSystem.md",
                    "basics/ContextualVariables.md",
                    "basics/Variable_metadata.md",
                    "basics/Composition.md",
                    "basics/Events.md",
                    "basics/Validation.md",
                    "basics/DependencyGraphs.md",
                    "basics/FAQ.md"],
    "System Types" => Any["systems/ODESystem.md",
                          "systems/SDESystem.md",
                          "systems/JumpSystem.md",
                          "systems/NonlinearSystem.md",
                          "systems/OptimizationSystem.md",
                          "systems/PDESystem.md"],
    "comparison.md",
    "internals.md",
]
