name: format-check

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  runic:
    name: "Runic"
    uses: "SciML/.github/.github/workflows/runic.yml@v1"
    secrets: "inherit"
