name: Sublibrary CI

on:
  pull_request:
    branches:
      - master
      - 'release-'
      - as/su-v4
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'benchmark/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  sublibrary-ci:
    uses: "SciML/.github/.github/workflows/sublibrary-tests.yml@v1"
    secrets: "inherit"
